const SUPABASE_URL="https://acfctgzevmstoqqhtwfs.supabase.co";
const SUPABASE_KEY="sb_publishable_7b9I48CTSngMxXthiYMvqQ_UeIwiFMs";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let me=null,page="home"; const app=document.getElementById("app");
const money=n=>`${Number(n||0).toFixed(2)} 🪙`;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(t){const x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2800)}
async function ensureProfile(u){let {data}=await sb.from("profiles").select("*").eq("id",u.id).maybeSingle();if(!data){await sb.from("profiles").insert({id:u.id,username:u.user_metadata?.username||u.email.split("@")[0]});data=(await sb.from("profiles").select("*").eq("id",u.id).single()).data}return data}
async function loadMe(u){me=await ensureProfile(u)}
function login(){app.innerHTML=`<div class="login card"><div class="logo">🐺 WOLF <span>BETS</span></div><p class="muted">Créditos ficticios · sistema multiusuario</p><div class="tabs"><button class="ghost" onclick="auth('in')">Entrar</button><button class="ghost" onclick="auth('up')">Crear cuenta</button></div><div id="authbox"></div></div>`;auth("in")}
function auth(mode){authbox.innerHTML=mode=="in"?`<form class="form" onsubmit="signin(event)"><input id="email" type="email" placeholder="Email" required><input id="password" type="password" placeholder="Contraseña" required><button class="primary">Entrar</button></form>`:`<form class="form" onsubmit="signup(event)"><input id="username" placeholder="Nombre de jugador" required><input id="email" type="email" placeholder="Email" required><input id="password" type="password" minlength="6" placeholder="Contraseña" required><button class="primary">Crear cuenta</button></form>`}
async function signin(e){e.preventDefault();let {data,error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error)return toast(error.message);await loadMe(data.user);go("home")}
async function signup(e){e.preventDefault();let {data,error}=await sb.auth.signUp({email:email.value,password:password.value,options:{data:{username:username.value.trim()}}});if(error)return toast(error.message);if(data.user){await loadMe(data.user);toast("Cuenta creada");go("home")}}
async function logout(){await sb.auth.signOut();me=null;login()}
function nav(){return `<header class="top"><div class="bar"><div class="logo">🐺 WOLF <span>BETS</span></div><div class="nav"><button onclick="go('home')">Partidos</button><button onclick="go('bets')">Mis apuestas</button><button onclick="go('ranking')">Ranking</button>${me.is_admin?`<button onclick="go('admin')">👑 Admin</button>`:""}</div><div class="balance">${me.is_admin?"♾️ 🪙":money(me.balance)}</div><button class="ghost" onclick="logout()">Salir</button></div></header>`}
async function go(p){page=p;await render()}
async function shell(c){app.innerHTML=nav()+`<main class="wrap">${c}</main>`}
async function render(){if(!me)return login();await loadMe((await sb.auth.getUser()).data.user);if(page=="home")return home();if(page=="bets")return bets();if(page=="ranking")return ranking();return admin()}
async function home(){let {data,error}=await sb.from("matches").select("*").eq("status","open").order("match_date");if(error)return toast(error.message);await shell(`<section class="hero"><h1>Buenas, ${esc(me.username)} 👋</h1><div class="muted">${me.is_admin?"Saldo ilimitado ♾️":"Saldo: "+money(me.balance)}</div></section><div class="grid">${data?.length?data.map(matchCard).join(""):`<div class="card center muted">No hay partidos abiertos.</div>`}</div>`)}
function matchCard(m){return `<article class="card"><div class="row"><span class="badge">ABIERTO</span><span class="small muted">${new Date(m.match_date).toLocaleString("es-ES")}</span></div><div class="teams">${esc(m.home)} <span class="muted">vs</span> ${esc(m.away)}</div><div class="market"><button class="odd" onclick="openBet(${m.id},'home',${m.odd_home})">1 · ${esc(m.home)}<b>${m.odd_home}</b></button><button class="odd" onclick="openBet(${m.id},'draw',${m.odd_draw})">X · Empate<b>${m.odd_draw}</b></button><button class="odd" onclick="openBet(${m.id},'away',${m.odd_away})">2 · ${esc(m.away)}<b>${m.odd_away}</b></button></div></article>`}
async function openBet(id,sel,odd){let {data:m}=await sb.from("matches").select("*").eq("id",id).single();let label=sel=="home"?m.home:sel=="away"?m.away:"Empate";await shell(`<div class="card"><h2>${esc(m.home)} vs ${esc(m.away)}</h2><p>${esc(label)} · Cuota <b>${odd}</b></p><form class="form" onsubmit="place(event,${id},'${sel}',${odd})"><input id="stake" type="number" min="1" max="${me.is_admin?999999999:Math.floor(me.balance)}" placeholder="Créditos" required><div class="row"><span>Posible cobro</span><b id="potential">0.00 🪙</b></div><button class="primary">Confirmar apuesta</button><button type="button" class="ghost" onclick="go('home')">Cancelar</button></form></div>`);stake.oninput=()=>potential.textContent=money(Number(stake.value||0)*odd)}
async function place(e,id,sel,odd){e.preventDefault();let amount=Number(stake.value);if(amount<=0)return toast("Importe inválido");let {error}=await sb.rpc("place_bet",{p_match_id:id,p_selection:sel,p_stake:amount});if(error)return toast(error.message);toast("Apuesta registrada");go("bets")}
async function bets(){let {data,error}=await sb.from("bets").select("*,matches(home,away,match_date)").eq("user_id",me.id).order("created_at",{ascending:false});if(error)return toast(error.message);await shell(`<section class="hero"><h1>Mis apuestas</h1></section><div class="card">${data?.length?data.map(b=>`<div class="ticket"><div><b>${esc(b.matches.home)} vs ${esc(b.matches.away)}</b><div class="small muted">${b.selection} · cuota ${b.odd} · ${money(b.stake)}</div></div><b>${b.status=="pending"?"PENDIENTE":b.status=="won"?"GANADA":"PERDIDA"}<br>${b.status=="won"?money(b.potential_win):""}</b></div>`).join(""):`<div class="center muted">No tienes apuestas.</div>`}</div>`)}
async function ranking(){let {data,error}=await sb.from("profiles").select("username,balance").eq("is_admin",false).order("balance",{ascending:false});if(error)return toast(error.message);await shell(`<section class="hero"><h1>🏆 Ranking</h1></section><div class="card"><table class="table"><tr><th>#</th><th>Jugador</th><th>Saldo</th></tr>${data.map((u,i)=>`<tr><td>${i+1}</td><td>${esc(u.username)}</td><td><b>${money(u.balance)}</b></td></tr>`).join("")}</table></div>`)}
async function admin(){if(!me.is_admin)return go("home");let [us,ms]=await Promise.all([sb.from("profiles").select("*").order("username"),sb.from("matches").select("*").order("match_date",{ascending:false})]);if(us.error||ms.error)return toast((us.error||ms.error).message);await shell(`<section class="hero adminbox"><h1>👑 Panel de control</h1><div class="muted">Saldo ilimitado · gestión de usuarios · partidos</div></section><div class="grid"><div class="card"><h2>Usuarios</h2>${us.data.filter(u=>!u.is_admin).map(u=>`<div class="ticket"><div><b>${esc(u.username)}</b><div class="small muted">${money(u.balance)}</div></div><div class="actions"><button class="danger" onclick="changeBalance('${u.id}',-100)">−100</button><button class="success" onclick="changeBalance('${u.id}',100)">+100</button><button class="success" onclick="changeBalance('${u.id}',500)">+500</button><button class="success" onclick="changeBalance('${u.id}',1000)">+1000</button></div></div>`).join("")}</div><div class="card"><h2>Crear partido</h2><form class="form" onsubmit="createMatch(event)"><input id="home" placeholder="Local" required><input id="away" placeholder="Visitante" required><input id="date" type="datetime-local" required><input id="oh" type="number" min="1.01" step=".01" placeholder="Cuota 1" required><input id="od" type="number" min="1.01" step=".01" placeholder="Cuota X" required><input id="oa" type="number" min="1.01" step=".01" placeholder="Cuota 2" required><button class="primary">Crear partido</button></form></div><div class="card"><h2>Resolver partidos</h2>${ms.data.map(m=>`<div class="ticket"><div><b>${esc(m.home)} vs ${esc(m.away)}</b><div class="small muted">${new Date(m.match_date).toLocaleString("es-ES")} · ${m.status}</div></div>${m.status=="open"?`<div class="actions"><button class="success" onclick="resolve(${m.id},'home')">1</button><button class="success" onclick="resolve(${m.id},'draw')">X</button><button class="success" onclick="resolve(${m.id},'away')">2</button></div>`:`<span class="badge">${esc(m.result||"RESUELTO")}</span>`}</div>`).join("")}</div></div>`)}
async function changeBalance(id,delta){let {error}=await sb.rpc("admin_adjust_balance",{p_user_id:id,p_delta:delta});if(error)return toast(error.message);toast("Saldo actualizado");render()}
async function createMatch(e){e.preventDefault();let {error}=await sb.from("matches").insert({home:home.value.trim(),away:away.value.trim(),match_date:new Date(date.value).toISOString(),odd_home:Number(oh.value),odd_draw:Number(od.value),odd_away:Number(oa.value),status:"open"});if(error)return toast(error.message);toast("Partido creado");render()}
async function resolve(id,result){let {error}=await sb.rpc("resolve_match",{p_match_id:id,p_result:result});if(error)return toast(error.message);toast("Partido resuelto");render()}
async function boot(){let {data}=await sb.auth.getSession();if(data.session){await loadMe(data.session.user);render()}else login()}boot();