-- ============================================================
-- PABLO23 BETS - ADMIN V3
-- Resultados + borrado seguro + SUPERCUOTAS
-- Compatible con matches(home, away, match_date, status,
-- odd_home, odd_draw, odd_away, result)
--
-- Ejecutar DESPUÉS del SQL maestro + ADMIN V2.
-- No borra datos existentes.
-- ============================================================

-- ------------------------------------------------------------
-- 1) Marcador del partido
-- ------------------------------------------------------------
alter table public.matches
    add column if not exists score_home integer;

alter table public.matches
    add column if not exists score_away integer;


-- ------------------------------------------------------------
-- 2) Tabla de SUPERCUOTAS
-- La cuota real que se usa para apostar sigue siendo markets.odd.
-- original_odd guarda la cuota anterior para poder restaurarla.
-- ------------------------------------------------------------
create table if not exists public.supercuotas(
    id bigint generated by default as identity primary key,
    market_id bigint not null unique
        references public.markets(id)
        on delete cascade,

    original_odd numeric(8,2) not null
        check(original_odd > 1),

    super_odd numeric(8,2) not null
        check(super_odd > 1),

    label text not null default 'SUPERCUOTA',
    image_url text,
    banner_url text,

    active boolean not null default true,
    expires_at timestamptz,
    sort_order integer not null default 0,

    created_at timestamptz not null default now()
);

alter table public.supercuotas enable row level security;

drop policy if exists "supercuotas readable"
on public.supercuotas;

drop policy if exists "admin manages supercuotas"
on public.supercuotas;

create policy "supercuotas readable"
on public.supercuotas
for select
to authenticated
using(
    active = true
    or public.is_admin()
);

create policy "admin manages supercuotas"
on public.supercuotas
for all
to authenticated
using(public.is_admin())
with check(public.is_admin());


-- ------------------------------------------------------------
-- 3) Actualizar resultado/marcador desde la web
-- ------------------------------------------------------------
create or replace function public.admin_update_match_result(
    p_match_id bigint,
    p_score_home integer default null,
    p_score_away integer default null,
    p_result text default null,
    p_status text default 'finished'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin

    if not public.is_admin() then
        raise exception 'No autorizado';
    end if;

    if p_score_home is not null and p_score_home < 0 then
        raise exception 'El marcador local no puede ser negativo';
    end if;

    if p_score_away is not null and p_score_away < 0 then
        raise exception 'El marcador visitante no puede ser negativo';
    end if;

    if p_result is not null
       and p_result not in ('home','draw','away') then
        raise exception 'Resultado inválido';
    end if;

    update public.matches
    set
        score_home = p_score_home,
        score_away = p_score_away,
        result = p_result,
        status = coalesce(nullif(trim(p_status), ''), status)
    where id = p_match_id;

    if not found then
        raise exception 'Partido no encontrado';
    end if;

end;
$$;

grant execute
on function public.admin_update_match_result(bigint,integer,integer,text,text)
to authenticated;


-- ------------------------------------------------------------
-- 4) Borrar partido de forma SEGURA
--
-- Si existen apuestas o selecciones de combinadas, NO permite
-- borrar físicamente el partido para no destruir historial.
-- En ese caso se debe cerrar/cancelar.
-- ------------------------------------------------------------
create or replace function public.admin_delete_match(
    p_match_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    bet_count integer;
    combo_count integer;
begin

    if not public.is_admin() then
        raise exception 'No autorizado';
    end if;

    select count(*)
    into bet_count
    from public.bets b
    where b.match_id = p_match_id;

    select count(*)
    into combo_count
    from public.combo_bet_legs cbl
    join public.markets m
      on m.id = cbl.market_id
    where m.match_id = p_match_id;

    if bet_count > 0 or combo_count > 0 then
        raise exception
            'No se puede borrar este partido porque ya tiene apuestas o combinadas. Ciérralo/cancélalo para conservar el historial.';
    end if;

    delete from public.matches
    where id = p_match_id;

    if not found then
        raise exception 'Partido no encontrado';
    end if;

end;
$$;

grant execute
on function public.admin_delete_match(bigint)
to authenticated;


-- ------------------------------------------------------------
-- 5) Borrar cuota/mercado de forma SEGURA
-- ------------------------------------------------------------
create or replace function public.admin_delete_market(
    p_market_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    bet_count integer;
    combo_count integer;
begin

    if not public.is_admin() then
        raise exception 'No autorizado';
    end if;

    select count(*)
    into bet_count
    from public.bets
    where market_id = p_market_id;

    select count(*)
    into combo_count
    from public.combo_bet_legs
    where market_id = p_market_id;

    if bet_count > 0 or combo_count > 0 then
        raise exception
            'No se puede borrar esta cuota porque ya tiene apuestas o forma parte de combinadas. Ciérrala para conservar el historial.';
    end if;

    delete from public.markets
    where id = p_market_id;

    if not found then
        raise exception 'Mercado no encontrado';
    end if;

end;
$$;

grant execute
on function public.admin_delete_market(bigint)
to authenticated;


-- ------------------------------------------------------------
-- 6) Crear / actualizar SUPERCUOTA
--
-- Al activarla:
--   markets.odd pasa a ser la supercuota.
--   original_odd conserva la cuota anterior.
--
-- Al desactivarla:
--   markets.odd vuelve a original_odd.
-- ------------------------------------------------------------
create or replace function public.admin_set_supercuota(
    p_market_id bigint,
    p_super_odd numeric,
    p_label text default 'SUPERCUOTA',
    p_image_url text default null,
    p_banner_url text default null,
    p_expires_at timestamptz default null,
    p_sort_order integer default 0
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    market_odd numeric;
    super_id bigint;
begin

    if not public.is_admin() then
        raise exception 'No autorizado';
    end if;

    if p_super_odd is null or p_super_odd <= 1 then
        raise exception 'La supercuota debe ser mayor que 1';
    end if;

    select odd
    into market_odd
    from public.markets
    where id = p_market_id
    for update;

    if not found then
        raise exception 'Mercado no encontrado';
    end if;

    -- Si ya existe una supercuota, mantenemos su original_odd.
    insert into public.supercuotas(
        market_id,
        original_odd,
        super_odd,
        label,
        image_url,
        banner_url,
        active,
        expires_at,
        sort_order
    )
    values(
        p_market_id,
        market_odd,
        p_super_odd,
        coalesce(nullif(trim(p_label),''),'SUPERCUOTA'),
        p_image_url,
        p_banner_url,
        true,
        p_expires_at,
        coalesce(p_sort_order,0)
    )
    on conflict(market_id)
    do update set
        super_odd = excluded.super_odd,
        label = excluded.label,
        image_url = excluded.image_url,
        banner_url = excluded.banner_url,
        active = true,
        expires_at = excluded.expires_at,
        sort_order = excluded.sort_order;

    -- Si la fila ya existía y estaba activa, su original_odd
    -- se conserva gracias al ON CONFLICT.
    update public.markets
    set
        odd = p_super_odd,
        is_open = true
    where id = p_market_id;

    select id
    into super_id
    from public.supercuotas
    where market_id = p_market_id;

    return super_id;
end;
$$;

grant execute
on function public.admin_set_supercuota(bigint,numeric,text,text,text,timestamptz,integer)
to authenticated;


-- ------------------------------------------------------------
-- 7) Activar/desactivar SUPERCUOTA
-- ------------------------------------------------------------
create or replace function public.admin_toggle_supercuota(
    p_market_id bigint,
    p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    original numeric;
begin

    if not public.is_admin() then
        raise exception 'No autorizado';
    end if;

    select original_odd
    into original
    from public.supercuotas
    where market_id = p_market_id
    for update;

    if not found then
        raise exception 'Este mercado no tiene supercuota';
    end if;

    if p_active then
        update public.supercuotas
        set active = true
        where market_id = p_market_id;

        update public.markets m
        set odd = (
            select s.super_odd
            from public.supercuotas s
            where s.market_id = m.id
        ),
        is_open = true
        where m.id = p_market_id;

    else
        update public.markets
        set odd = original
        where id = p_market_id;

        update public.supercuotas
        set active = false
        where market_id = p_market_id;
    end if;

end;
$$;

grant execute
on function public.admin_toggle_supercuota(bigint,boolean)
to authenticated;


-- ------------------------------------------------------------
-- 8) Limpiar supercuotas expiradas
--    No lo ejecutamos automáticamente en cada apuesta; el frontend
--    puede refrescar y el admin también puede desactivarlas.
-- ------------------------------------------------------------
create or replace function public.expire_supercuotas()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    n integer;
begin

    update public.markets m
    set odd = s.original_odd
    from public.supercuotas s
    where s.market_id = m.id
      and s.active = true
      and s.expires_at is not null
      and s.expires_at <= now();

    update public.supercuotas
    set active = false
    where active = true
      and expires_at is not null
      and expires_at <= now();

    get diagnostics n = row_count;
    return n;
end;
$$;

grant execute
on function public.expire_supercuotas()
to authenticated;


-- ------------------------------------------------------------
-- 9) Índices
-- ------------------------------------------------------------
create index if not exists idx_supercuotas_active_order
on public.supercuotas(active, sort_order, expires_at);

create index if not exists idx_matches_result
on public.matches(status, match_date);


-- ============================================================
-- FIN ADMIN V3
-- ============================================================

-- ------------------------------------------------------------
-- 10) Marcar una selección concreta como NO PASADA
--     No resuelve las otras selecciones pendientes del mismo mercado.
--     Sí marca como perdida la selección en simples/combinadas.
-- ------------------------------------------------------------
create or replace function public.admin_mark_selection_lost(
    p_market_id bigint,
    p_selection text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    b record;
    cb record;
begin
    if not public.is_admin() then
        raise exception 'No autorizado';
    end if;

    if trim(coalesce(p_selection,'')) = '' then
        raise exception 'Selección vacía';
    end if;

    for b in
        select * from public.bets
        where market_id = p_market_id
          and status = 'pending'
          and lower(trim(selection)) = lower(trim(p_selection))
    loop
        update public.bets
        set status = 'lost'
        where id = b.id;
    end loop;

    update public.combo_bet_legs
    set status = 'lost'
    where market_id = p_market_id
      and status = 'pending'
      and lower(trim(selection)) = lower(trim(p_selection));

    -- Toda combinada que ya tenga una pata perdida queda perdida.
    for cb in
        select distinct combo_bet_id
        from public.combo_bet_legs
        where market_id = p_market_id
    loop
        if exists(
            select 1 from public.combo_bet_legs
            where combo_bet_id = cb.combo_bet_id
              and status = 'lost'
        ) then
            update public.combo_bets
            set status = 'lost'
            where id = cb.combo_bet_id
              and status = 'pending';
        end if;
    end loop;
end;
$$;

grant execute
on function public.admin_mark_selection_lost(bigint,text)
to authenticated;

-- ============================================================
-- FIN ADMIN V3 + SUPERCUOTAS + RESULTADO DE SELECCIÓN
-- ============================================================
